spring:
  redis:
    host: 114.55.87.108
    port: 6379
    password: bt_redis
    database: 0
    lettuce:
      pool:
        max-active: 300
  datasource:
    url: jdbc:mysql://114.55.87.108:3306/wk_hrm_single?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: d977f73e6c87f612
mybatis-plus:
  configuration:
    call-setters-on-nulls: true