xxl:
  job:
    admin:
      addresses: http://114.55.87.108:9180/xxl-job-admin
    executor:
      appname: nmlk-job
      ip:
      port: 9998
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken: 2266a2d0b9354d6590f350888d2938af
spring:
  redis:
    host: 114.55.87.108
    port: 6379
    password: bt_redis
    database: 0
    lettuce:
      pool:
        max-active: 300
  datasource:
    url: jdbc:mysql://114.55.87.108:3306/wk_crm_single?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: d977f73e6c87f612

